name: Container CI

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v1

      - name: Build containers
        if: success()
        run: |
          tar -C keycloak-adapter-app-build -czh . \
            | docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY/keycloak-adapter-app-build:${{ github.sha }} -
          tar -C keycloak-extension-build -czh . \
            | docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY/keycloak-extension-build:${{ github.sha }} -
          tar -C midpoint-extension-build -czh . \
            | docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY/midpoint-extension-build:${{ github.sha }} -

