name: Container CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        if: success()
        with:
          login-server: docker.pkg.github.com
          username: ${GITHUB_ACTOR}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build containers
        if: success()
        run: |
          tar -C keycloak-adapter-app-build -czh . \
            | docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY/keycloak-adapter-app-build:${{ github.sha }} -

      - name: Push containers
        if: success()
        run: |
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/keycloak-adapter-app-build:${{ github.sha }}

