name: Release keycloak-adapter-app-build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        if: success()
        with:
          #login-server: docker.pkg.github.com
          # username: ${GITHUB_ACTOR}
          # password: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push container
        if: success()
        run: |
          . versions.sh
          echo "KEYCLOAK=$KEYCLOAK"
          echo "SPRING_BOOT=$SPRING_BOOT"
          export IMAGE_TAG=${KEYCLOAK}_${SPRING_BOOT}

          tar -C keycloak-adapter-app-build -czh . \
            | docker build -t openstandia/keycloak-adapter-app-build:${IMAGE_TAG} -
          docker push openstandia/keycloak-adapter-app-build:${IMAGE_TAG}

