name: Container CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        if: success()
        with:
          #login-server: docker.pkg.github.com
          # username: ${GITHUB_ACTOR}
          # password: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build containers
        if: success()
        run: |
          tar -C keycloak-adapter-app-build -czh . \
            | docker build -t openstandia/keycloak-adapter-app-build:${{ github.sha }} -
          tar -C keycloak-extension-build -czh . \
            | docker build -t openstandia/keycloak-extension-build:${{ github.sha }} -
          tar -C midpoint-extension-build -czh . \
            | docker build -t openstandia/midpoint-extension-build:${{ github.sha }} -

      - name: Push containers
        if: success()
        run: |
          docker push openstandia/keycloak-adapter-app-build:${{ github.sha }}
          docker push openstandia/keycloak-extension-build:${{ github.sha }}
          docker push openstandia/midpoint-extension-build:${{ github.sha }}

